app:
  env: dev
  port: 3000
  
postgres:
  db_host: localhost
  db_port: 5432
  username: soulisack
  password: 77477686
  db_name: godb
# app:
#   port:

# mysql:
#   db_host: 
#   db_port: 
#   username: 
#   password: 
#   db_name: 

# postgres:
#   db_host: 
#   db_port: 
#   username: 
#   password: 
#   db_name:

# jwt:
#   access_token:
#   refresh_token: