// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MessageResponse struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Product struct {
	ID    int32   `json:"ID"`
	Name  string  `json:"Name"`
	Price float64 `json:"Price"`
	Owner *User   `json:"Owner"`
}

type ProductReq struct {
	Name   string  `json:"Name"`
	Price  float64 `json:"Price"`
	UserID int32   `json:"UserID"`
}

type Query struct {
}

type User struct {
	ID       int32      `json:"ID"`
	Name     string     `json:"Name"`
	Email    string     `json:"Email"`
	Products []*Product `json:"Products"`
}

type UserInfo struct {
	Name  string `json:"Name"`
	Email string `json:"Email"`
}
